name: 'OVH DNS zone import'
author: Pierre Prinetti
description: 'Import a DNS zone BIND file to the OVH API.'
branding:
  icon: align-left
  color: blue
inputs:
  zone-file:
    description: 'Zone file to apply'
    required: true
  zone-name:
    description: 'Domain name where to apply the zone file'
    required: true
outputs:
  response:
    description: 'The response of the server'
runs:
  using: 'node16'
  main: 'index.js'
